// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/lp_rpc.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TranscoderRequest struct {
	JobId                int64    `protobuf:"varint,1,opt,name=jobId" json:"jobId,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranscoderRequest) Reset()         { *m = TranscoderRequest{} }
func (m *TranscoderRequest) String() string { return proto.CompactTextString(m) }
func (*TranscoderRequest) ProtoMessage()    {}
func (*TranscoderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lp_rpc_fe30712173eb1f14, []int{0}
}
func (m *TranscoderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscoderRequest.Unmarshal(m, b)
}
func (m *TranscoderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscoderRequest.Marshal(b, m, deterministic)
}
func (dst *TranscoderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscoderRequest.Merge(dst, src)
}
func (m *TranscoderRequest) XXX_Size() int {
	return xxx_messageInfo_TranscoderRequest.Size(m)
}
func (m *TranscoderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscoderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TranscoderRequest proto.InternalMessageInfo

func (m *TranscoderRequest) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *TranscoderRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type TranscoderReply struct {
	Transcoder           string   `protobuf:"bytes,1,opt,name=transcoder" json:"transcoder,omitempty"`
	ManifestUri          string   `protobuf:"bytes,2,opt,name=manifestUri" json:"manifestUri,omitempty"`
	AuthType             string   `protobuf:"bytes,3,opt,name=authType" json:"authType,omitempty"`
	Credentials          string   `protobuf:"bytes,4,opt,name=credentials" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranscoderReply) Reset()         { *m = TranscoderReply{} }
func (m *TranscoderReply) String() string { return proto.CompactTextString(m) }
func (*TranscoderReply) ProtoMessage()    {}
func (*TranscoderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lp_rpc_fe30712173eb1f14, []int{1}
}
func (m *TranscoderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscoderReply.Unmarshal(m, b)
}
func (m *TranscoderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscoderReply.Marshal(b, m, deterministic)
}
func (dst *TranscoderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscoderReply.Merge(dst, src)
}
func (m *TranscoderReply) XXX_Size() int {
	return xxx_messageInfo_TranscoderReply.Size(m)
}
func (m *TranscoderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscoderReply.DiscardUnknown(m)
}

var xxx_messageInfo_TranscoderReply proto.InternalMessageInfo

func (m *TranscoderReply) GetTranscoder() string {
	if m != nil {
		return m.Transcoder
	}
	return ""
}

func (m *TranscoderReply) GetManifestUri() string {
	if m != nil {
		return m.ManifestUri
	}
	return ""
}

func (m *TranscoderReply) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

func (m *TranscoderReply) GetCredentials() string {
	if m != nil {
		return m.Credentials
	}
	return ""
}

type AuthToken struct {
	StreamId             string   `protobuf:"bytes,1,opt,name=streamId" json:"streamId,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthToken) Reset()         { *m = AuthToken{} }
func (m *AuthToken) String() string { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()    {}
func (*AuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_lp_rpc_fe30712173eb1f14, []int{2}
}
func (m *AuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthToken.Unmarshal(m, b)
}
func (m *AuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthToken.Marshal(b, m, deterministic)
}
func (dst *AuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthToken.Merge(dst, src)
}
func (m *AuthToken) XXX_Size() int {
	return xxx_messageInfo_AuthToken.Size(m)
}
func (m *AuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthToken proto.InternalMessageInfo

func (m *AuthToken) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *AuthToken) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*TranscoderRequest)(nil), "server.TranscoderRequest")
	proto.RegisterType((*TranscoderReply)(nil), "server.TranscoderReply")
	proto.RegisterType((*AuthToken)(nil), "server.AuthToken")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrchestratorClient interface {
	// Gets transcoder information for a job
	GetTranscoder(ctx context.Context, in *TranscoderRequest, opts ...grpc.CallOption) (*TranscoderReply, error)
}

type orchestratorClient struct {
	cc *grpc.ClientConn
}

func NewOrchestratorClient(cc *grpc.ClientConn) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) GetTranscoder(ctx context.Context, in *TranscoderRequest, opts ...grpc.CallOption) (*TranscoderReply, error) {
	out := new(TranscoderReply)
	err := c.cc.Invoke(ctx, "/server.Orchestrator/GetTranscoder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Orchestrator service

type OrchestratorServer interface {
	// Gets transcoder information for a job
	GetTranscoder(context.Context, *TranscoderRequest) (*TranscoderReply, error)
}

func RegisterOrchestratorServer(s *grpc.Server, srv OrchestratorServer) {
	s.RegisterService(&_Orchestrator_serviceDesc, srv)
}

func _Orchestrator_GetTranscoder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscoderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetTranscoder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Orchestrator/GetTranscoder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetTranscoder(ctx, req.(*TranscoderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orchestrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTranscoder",
			Handler:    _Orchestrator_GetTranscoder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/lp_rpc.proto",
}

func init() { proto.RegisterFile("server/lp_rpc.proto", fileDescriptor_lp_rpc_fe30712173eb1f14) }

var fileDescriptor_lp_rpc_fe30712173eb1f14 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x89, 0xd1, 0xc3, 0x8c, 0x27, 0xea, 0x2a, 0x18, 0xaf, 0x90, 0x90, 0xea, 0xaa, 0x08,
	0x5a, 0x89, 0x95, 0x58, 0x88, 0x95, 0xb0, 0x9e, 0xb5, 0xec, 0x25, 0xa3, 0x17, 0xcd, 0x65, 0xd7,
	0x99, 0x39, 0x21, 0x3f, 0xc3, 0x7f, 0x2c, 0x49, 0x24, 0x2e, 0xc4, 0x6e, 0xdf, 0x37, 0xfb, 0x1e,
	0xbc, 0x07, 0xc7, 0x8c, 0xf4, 0x85, 0x74, 0x51, 0xb9, 0x17, 0x72, 0x79, 0xe6, 0xc8, 0x8a, 0x55,
	0x93, 0x1e, 0xa6, 0x37, 0x70, 0xb4, 0x20, 0x53, 0x73, 0x6e, 0x0b, 0x24, 0x8d, 0x9f, 0x1b, 0x64,
	0x51, 0x27, 0xb0, 0xf3, 0x6e, 0x97, 0x0f, 0x45, 0x1c, 0x24, 0xc1, 0x3c, 0xd4, 0xbd, 0x50, 0x87,
	0x10, 0x72, 0xf9, 0x16, 0x6f, 0x25, 0xc1, 0x7c, 0xaa, 0xdb, 0x67, 0xfa, 0x1d, 0xc0, 0x81, 0xef,
	0x76, 0x55, 0xa3, 0xce, 0x01, 0x64, 0x40, 0x5d, 0x40, 0xa4, 0x3d, 0xa2, 0x12, 0xd8, 0x5b, 0x9b,
	0xba, 0x7c, 0x45, 0x96, 0x67, 0x2a, 0xbb, 0xb4, 0x48, 0xfb, 0x48, 0xcd, 0x60, 0xd7, 0x6c, 0x64,
	0xb5, 0x68, 0x1c, 0xc6, 0x61, 0x77, 0x1e, 0x74, 0xeb, 0xce, 0x09, 0x0b, 0xac, 0xa5, 0x34, 0x15,
	0xc7, 0xdb, 0xbd, 0xdb, 0x43, 0xe9, 0x35, 0x44, 0xb7, 0xed, 0x6f, 0xfb, 0x81, 0x75, 0x1b, 0xc5,
	0x42, 0x68, 0xd6, 0xbf, 0x5d, 0x22, 0x3d, 0xe8, 0x71, 0x9d, 0xcb, 0x27, 0x98, 0x3e, 0x52, 0xbe,
	0x42, 0x16, 0x32, 0x62, 0x49, 0xdd, 0xc1, 0xfe, 0x3d, 0xca, 0x5f, 0x41, 0x75, 0x96, 0xf5, 0xab,
	0x65, 0xa3, 0xc9, 0x66, 0xa7, 0xff, 0x9d, 0x5c, 0xd5, 0x2c, 0x27, 0xdd, 0xde, 0x57, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x00, 0xaf, 0x00, 0x63, 0x86, 0x01, 0x00, 0x00,
}
